## Copyright (C) 2013 Lars Simon Zehnder
#
# This file is part of finmix.
#
# finmix is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# finmix is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rcpp.  If not, see <http://www.gnu.org/licenses/>.

#This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swap_cc <- function(values, index) {
    .Call('finmix_swap_cc', PACKAGE = 'finmix', values, index)
}

swapInteger_cc <- function(values, index) {
    .Call('finmix_swapInteger_cc', PACKAGE = 'finmix', values, index)
}

swapInd_cc <- function(values, index) {
    .Call('finmix_swapInd_cc', PACKAGE = 'finmix', values, index)
}

swapST_cc <- function(values, index) {
    .Call('finmix_swapST_cc', PACKAGE = 'finmix', values, index)
}

