# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swap_cc <- function(values, index) {
    .Call('finmix_swap_cc', PACKAGE = 'finmix', values, index)
}

swap_cc2 <- function(values, index) {
    .Call('finmix_swap_cc2', PACKAGE = 'finmix', values, index)
}

swapInd_cc <- function(values, index) {
    .Call('finmix_swapInd_cc', PACKAGE = 'finmix', values, index)
}

swapST_cc <- function(values, index) {
    .Call('finmix_swapST_cc', PACKAGE = 'finmix', values, index)
}

