# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swap_cc <- function(values, index) {
    .Call('finmix_swap_cc', PACKAGE = 'finmix', values, index)
}

swapInteger_cc <- function(values, index) {
    .Call('finmix_swapInteger_cc', PACKAGE = 'finmix', values, index)
}

swapInd_cc <- function(values, index) {
    .Call('finmix_swapInd_cc', PACKAGE = 'finmix', values, index)
}

swapST_cc <- function(values, index) {
    .Call('finmix_swapST_cc', PACKAGE = 'finmix', values, index)
}

ldgamma_cc <- function(values, shape, rate) {
    .Call('finmix_ldgamma_cc', PACKAGE = 'finmix', values, shape, rate)
}

dgamma_cc <- function(values, shape, rate) {
    .Call('finmix_dgamma_cc', PACKAGE = 'finmix', values, shape, rate)
}

lddirichlet_cc <- function(values, par) {
    .Call('finmix_lddirichlet_cc', PACKAGE = 'finmix', values, par)
}

ddirichlet_cc <- function(values, par) {
    .Call('finmix_ddirichlet_cc', PACKAGE = 'finmix', values, par)
}

maxlabel_poisson_cc <- function(values1, values2, shape, rate, dirich, perm) {
    .Call('finmix_maxlabel_poisson_cc', PACKAGE = 'finmix', values1, values2, shape, rate, dirich, perm)
}

hungarian_cc <- function(cost) {
    .Call('finmix_hungarian_cc', PACKAGE = 'finmix', cost)
}

stephens1997b_poisson_cc <- function(values, comp_par, weight_par) {
    .Call('finmix_stephens1997b_poisson_cc', PACKAGE = 'finmix', values, comp_par, weight_par)
}

